name: Test Python Package

on:
  push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout resource
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -e '.[testing]'

    - name: Test package
      run: python -m pytest tests --cov=httpie_oauth2_client_credentials --cov-report=html:build/coverage --capture=no

    - name: Build package
      run: python -m build
